- name: Run PostgreSQL using Docker
  hosts: localhost
  become: yes
  vars:
    pg_user: myuser
    pg_password: mypassword
    pg_database: mydatabase
    pg_container_name: postgres_db
    pg_port: 5432

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull PostgreSQL image
      docker_image:
        name: postgres
        source: pull

    - name: Run PostgreSQL container
      docker_container:
        name: "{{ pg_container_name }}"
        image: postgres
        state: started
        restart_policy: always
        ports:
          - "{{ pg_port }}:5432"
        env:
          POSTGRES_USER: "{{ pg_user }}"
          POSTGRES_PASSWORD: "{{ pg_password }}"
          POSTGRES_DB: "{{ pg_database }}"
        volumes:
          - pgdata:/var/lib/postgresql/data

    - name: Wait for PostgreSQL to become available
      wait_for:
        host: "127.0.0.1"
        port: "{{ pg_port }}"
        timeout: 30

  volumes:
    pgdata: {}

